theme: jekyll-theme-slate
title: keyPrefix
description: A Windows application to add custom prefix/suffix to keyboard input.
exclude:
  - installer/
google_site_verification: rC7e0y7XV5NeXF7bkRQVYt6N2GWhx_lG6vf7Nb3sW3Q
